//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApplicationMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReturn
    {
        public int Return_ID { get; set; }
        public int Book_ID { get; set; }
        public string BookName { get; set; }
        public System.DateTime BookIssueDate { get; set; }
        public System.DateTime BookReturnDate { get; set; }
    }
}
