//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApplicationMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue
    {
        public int Issue_ID { get; set; }
        public int StudentID { get; set; }
        public string Student_Name { get; set; }
        public string Department { get; set; }
        public string Student_Semester { get; set; }
        public int Student_Contact { get; set; }
        public string Student_Email { get; set; }
        public System.DateTime BookIssue_Date { get; set; }
        public string Book_Name { get; set; }
        public int Student_ID { get; set; }
        public int Book_ID { get; set; }
    }
}
