//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApplicationMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryManagementEntities : DbContext
    {
        public LibraryManagementEntities()
            : base("name=LibraryManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookIssue> BookIssues { get; set; }
        public virtual DbSet<BookReturn> BookReturns { get; set; }
        public virtual DbSet<BooksInfoEntry> BooksInfoEntries { get; set; }
        public virtual DbSet<StudentInfoEntry> StudentInfoEntries { get; set; }
        public virtual DbSet<vwBook> vwBooks { get; set; }
        public virtual DbSet<vwData> vwDatas { get; set; }
        public virtual DbSet<vwStudent> vwStudents { get; set; }
    }
}
