//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApplicationMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfoEntry
    {
        public int Student_ID { get; set; }
        public string Student_Name { get; set; }
        public int Enrollment_No { get; set; }
        public string Department { get; set; }
        public string Student_Semester { get; set; }
        public string Student_Contact { get; set; }
        public string Student_Email { get; set; }
    }
}
