//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebApplicationMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwData
    {
        public int Book_ID { get; set; }
        public string Book_Name { get; set; }
        public string Author_Name { get; set; }
        public string Publication { get; set; }
        public System.DateTime Purchase_Date { get; set; }
        public Nullable<decimal> Book_Price { get; set; }
        public Nullable<int> Books_Quantity { get; set; }
        public string Student_Name { get; set; }
    }
}
